# This is a template for a shell script that can be used to run the Snappy jar.
# DO NOT EDIT THIS FILE. Instead, copy it to a new file and edit that file.

#!/bin/bash

java -jar /etc/snappy/bin/snappy.jar "$@"
